version: '3.8'

services:
  family-budget-bot:
    build: .
    image: zorovr/tgbotlog-family-budget-bot:tag  # Укажите здесь нужное имя
    container_name: family-budget-bot
    restart: unless-stopped
    volumes:
      - budget-data:/app/database
      - ./appsettings.json:/app/appsettings.json:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

volumes:
  budget-data: